### ISSUE TITLE
Safari 9 scroll is either 1 or -1

### ISSUE THREAD

**Issue by drewbaker** [jquery/jquery-mousewheel#156]
On Safari 9.0 (the latest), `event.deltaY` is either 1, or -1. It never goes any higher than that. So it's not consistent across browsers. On Chrome it works fine.

![screen shot 2015-10-22 at 11 30 56 am](https://cloud.githubusercontent.com/assets/475015/10674552/6649e668-78b0-11e5-9ba9-d446b258572f.png)

![screen shot 2015-10-22 at 11 31 05 am](https://cloud.githubusercontent.com/assets/475015/10674550/64658366-78b0-11e5-8abf-4aee76d521bb.png)

**Comment by dmethvin** [comment]
I don't have a Mac with iOS to try this on so others will need to provide some more detail. Did Safari make some kind of intentional change here? You're saying the `event.deltaY` value provided by the plugin is only 1 or -1, what are the raw values Safari is giving?

**Comment by drewbaker** [comment]
It's strange, because it works with the mouse wheel on my logitech mouse, but if I use the trackpad, it is just -1 or 1. Chrome and Firefox is fine.

Here is a screenshot of the entire event, when using trackpad:
![screen shot 2015-10-22 at 1 38 57 pm](https://cloud.githubusercontent.com/assets/475015/10677674/b19d99d6-78c2-11e5-83d0-334ad3ae6a3b.png)

And here it is when using mousewheel on external mouse:
![screen shot 2015-10-22 at 1 40 52 pm](https://cloud.githubusercontent.com/assets/475015/10677690/c4a22cd6-78c2-11e5-94a2-24456ddc5cba.png)

**Comment by christian-thomas** [comment]
I've also got the same issue — All other browsers are fine, it's just the latest version of Safari that's giving 1/-1.

**Comment by dmethvin** [comment]
Put a breakpoint inside the plugin, on [this line](https://github.com/jquery/jquery-mousewheel/blob/b1c062e93b44f473022297c386d57fa7e58b6aae/jquery.mousewheel.js#L106). What path does Safari 9 take, and what values does it calculate? How does that differ from Safari 8?

**Comment by christian-thomas** [comment]
So, from a brief bit of debugging, I amended lines 106-108:

        if ( 'detail'      in orgEvent ) { deltaY = orgEvent.detail * -1;console.log('detail - ' + deltaY);      }
        if ( 'wheelDelta'  in orgEvent ) { deltaY = orgEvent.wheelDelta;console.log('wheelDelta - ' + deltaY);      }
        if ( 'wheelDeltaY' in orgEvent ) { deltaY = orgEvent.wheelDeltaY;console.log('wheelDeltaY - ' + deltaY);      }

It looks like Safari 9 has some sort of debouncing...

In Safari 8, depending how much I scroll, in a single mousewheel motion/scroll I'll get something like this:

		[Log] detail - 0
		[Log] wheelDelta - -60
		[Log] wheelDeltaY - -60
		[Log] detail - 0
		[Log] wheelDelta - -30
		[Log] wheelDeltaY - -30
		[Log] detail - 0
		[Log] wheelDelta - -90
		[Log] wheelDeltaY - -90

Safari 9:

		[Log] detail - 0
		[Log] wheelDelta - -3
		[Log] wheelDeltaY - -3

**Comment by Awea** [comment]
Hi there, any idea for a crappy work around for this one ?

**Comment by dmethvin** [comment]
It seems like it might be due to this Webkit bug reported by @mzgol : https://bugs.webkit.org/show_bug.cgi?id=149526

**Comment by kpettinga** [comment]
Experiencing the same issue over here as well. Is this something we'll have to wait for Safari or Webkit to fix?

**Comment by jrobson153** [comment]
I'm not sure if this helps, but I've found a workaround for this. In my situation I'm trying to detect the deltaY when scrolling a non-scrollable page and use the value. Like everyone else I get a totally normal value in chrome and FF, but in Safari I just get 1 or -1 when using a magic mouse or trackpad:

![screen shot 2016-02-17 at 2 05 24 pm](https://cloud.githubusercontent.com/assets/6475336/13126581/e2cc3994-d57f-11e5-85dc-d0e427d9182c.png)

It seems like this is being caused in part by the elastic scrolling that safari does. If the default scrolling behavior is disabled before using the deltaY value then the normal value comes through fine. The two easiest ways to achieve this:

1. Put `overflow: hidden;` on the body. This disables all scrolling
2. Add `event.preventDefault();` before using `event.deltaY`. This will kill the default mousewheel behavior

Either of those fix it for me both using the mousewheel plugin and the underlying 'mousewheel' event. This obviously won't help if the default scrolling behavior needs to stay in tact, but worked great for my situation.

**Comment by dmethvin** [comment]
Nice detective work there @jrobson153! This leads me to think that there isn't a solution that the plugin can automatically implement to solve this because either of those has tradeoffs. If I knew of anyone at Apple I could escalate this to I would, but Apple isn't known for its responsiveness on browser issues. What would be the best place to document this, perhaps the README.md file?

**Comment by jrobson153** [comment]
Yea, it could take them a while to catch up to this. I think a brief note in the Readme file would be helpful!

**Comment by dmethvin** [comment]
Did this get fixed in Safari 9.1?

**Comment by mgol** [comment]
I can no longer reproduce my test case from https://bugs.webkit.org/show_bug.cgi?id=149526. I've changed the MacBook from the last time I tried it, though so I can't be sure it didn't change something.

Could someone from the people that experienced the bug before check it on Safari 9.1?

**Comment by mgol** [comment]
My initial comment was wrong, the bug https://bugs.webkit.org/show_bug.cgi?id=149526 is still present in Safari 9.1.

**Comment by sandrodz** [comment]
ah Safari... new IE never fails to deliver bogus issues, its been 2 years now this has not been fixed?

**Comment by jmzhang** [comment]
This might be a simpler workaround: do not scroll your content within `body`, wrap your stuff inside another div that has a fixed height (e.g. 100vh), and bind the scroll event listener on that div. 

Here is a demo (cloned from the bug report and slightly modified): [http://output.jsbin.com/suwatixaxu](http://output.jsbin.com/suwatixaxu)

One caveat though: this will break the minimal-ui on mobile safari as it depends on scrolling within the body.

**Comment by pixelass** [comment]
Here's another approach to fixing the issue: https://github.com/pixelass/onwheel-fix

drawbacks: no elastic scroll in Safari 9 & 10 body.

* No css hacks
* No extra markup
* just `init` or `destroy` the fix when needed

It really just fixes the mousewheel bug where it occurs, by preventing the default event and reassigning the `event.deltaY` to `element.scrollTop`.


I tested it in Safari 9 & 10 with jQuery.mousewheel: [Codepen Demo](http://s.codepen.io/pixelass/debug/9dc4ac4331d1cd2a9b19e67da6e5fda1)

The demo has nested elements with different overflows. The demo has a header that should scroll in and out on `mousewheel`. Look at the console to check the returned `event.deltaX` & `event.deltaY`

<img width="226" alt="screen shot 2016-09-22 at 8 37 19 pm" src="https://cloud.githubusercontent.com/assets/1148334/18761242/70a3d7b0-8104-11e6-8aca-a98990b185e2.png">


> I did not write this to fix jQuery.mousewheel. This is a general fix that just turns out to work nicely with jQuery.mousewheel.

**Comment by pixelass** [comment]
Also.. the sad note is: It is still broken in Safari 10.

**Comment by ovokuro** [comment]
@pixelass I tried adding your fix, however I'm fairly new to javascript and not sure how to integrate it with the mousewheel code. The console tells me 'import' isn't recognised. 
My code is something like this:

```
jQuery("#container").mousewheel(function(event,delta) {
                    this.scrollLeft -= (delta * 30);
                    event.preventDefault();
                });
```

Should I include the fix within that?

**Comment by pixelass** [comment]
@ovokuro you can try including it as a script

```html
<script src="https://cdn.rawgit.com/pixelass/onwheel-fix/v0.3.3/dist/onwheel-fix.min.js"/>
```

I'm not sure about your setup.

`import foo from 'foo'` requires a build process that handles es6.

if you are loading jQuery and plugins in the head or body you should do the same for other scripts

<img width="706" alt="screen shot 2016-10-11 at 9 16 34 pm" src="https://cloud.githubusercontent.com/assets/1148334/19284904/2b187766-8ff8-11e6-86a6-dbd2d7bdfdec.png">


after those scripts add a script tag with this content: (or load another script that contains this content)

```js
var outerWheel = new FixWheel('wheel');
outerWheel.init(document.body);
```

Hope this helps

**Comment by JustinHu1988** [comment]
In my computer, when I scroll the mousewheel, all broswers(chrome/IE11/firefox) will give either 1 or -1 for event.deltaY. Why people here can get different value for event.deltaY? Which is normal?

![001](https://cloud.githubusercontent.com/assets/14176666/19295278/1fa1a2b8-9066-11e6-9007-b1fae8928aa5.png)

**Comment by ovokuro** [comment]
Thanks for your help @pixelass. Much appreciated.
Seems the problem I'm getting (erratic speeds) is only with a logitech mouse after updating to Sierra. Site worked fine on previous versions, and still works fine with apple mouse.

**Comment by pixelass** [comment]
@JustinHu1988 you should get different values:  
`[-1, 20, 108,  -45, -10, 0]` are all valid values.

You should check for other implementations or some example pages. If the issue only occurs on your own implementation there is most likely a bug in your code. You should create a demo which is not hosted in an iframe. This will help us understand what's going wrong.

@ovokuro   
* which mouse model do you have (exact product name). 
* Does the issue only occur in Safari or are other browsers affected?
* describe erratic speed
* does the issue occur without my plugin?

**Comment by JustinHu1988** [comment]
I've write a demo for this problem, I've tried in different computers, the event.deltaY is always 1 or -1. Maybe there are some problem in my code. This code in zip contains two online js files(jquery-1.7.2.min.js and jquery.mousewheel.min.js), they may not load smoothly, you can change it with your local file. 
[demo-for-mousewheel.zip](https://github.com/jquery/jquery-mousewheel/files/532509/demo-for-mousewheel.zip)

**Comment by ovokuro** [comment]
@pixelass 

It was actually a Targus mouse: AMU3301EUM. 
The site I've made scrolls horizontally. When I first used the mousewheel plugin I set the delta to 60 and it scrolled well on everything except trackpads on apple laptops - it was scrolling from one end of the page to the other instantly. I found a solution for this problem in the OSX inertia thread:
```
if (isMac) {
                this.scrollLeft -= (delta * 2);
            } else {
                this.scrollLeft -= (delta * 30);
            }
```
The site then seemed to scroll well on all browsers and devices. The designer I'm working with then updated her system to Sierra and found the scrolling really fast again, but some scrolls moved the page further than others. This was happening on Chrome and Safari, and only occurred with the Targus mouse. I then tried your plugin but it didn't seem to make a difference, so I've removed it. 

Now, for some reason (maybe driver updates?), the scrolling has settled a bit with the Targus mouse but is still a bit jerky. 

Let me know if you need more info.

**Comment by anojht** [comment]
Im not sure if this helps but I had scrolling issues on mac whereby scroll event was being fired more than once and causing pages to scroll more than intended. So eventually we implemented the following it is working on mac without causing issues on other platforms: [cubetransition](https://github.com/HTML50/cubeTransition.js/issues/2)

The code above detects scroll events over duration of time and determines if being fired by a mouse or a track pad then gives you the option to deal with it accordingly. If it is a track pad then it disable extra scroll behavior with a timeout function.

**Comment by skiokko** [comment]
Still broken on Latest Safari (04/12/2017)
Incredible

**Comment by pixelass** [comment]
@skiokko I don't think the safari team considers this to be a bug.

**Comment by skiokko** [comment]
I agree. The bug is from the plugin not from Safari.

**Comment by skiokko** [comment]
I fixed it but use a simple js code:

```
 document.getElementById('main').addEventListener('wheel', function (event) {
                console.log(event.deltaY)
 });
```

The plugin is not required.

**Comment by mgol** [comment]
> I agree. The bug is from the plugin not from Safari.

No, this *is* a Safari bug, see https://bugs.webkit.org/show_bug.cgi?id=149526. Your code is not adding a listener to the document but to a specific element so it's not hitting the issue.

**Comment by dmethvin** [comment]
See the Safari bug above for any updates on whether or when Safari will fix it. There is no way to fix it in the mousewheel plugin because Safari isn't giving us the information we need.

**Comment by mgol** [comment]
The issue was fixed in Safari 10; the current version is 18.3.1. We no longer need to care about Safari 9, so I'm closing the issue.
